api_version = "2025-04"
uid = "549b46d9-875d-dae8-8c02-557a562b910ab0c0ca0b"

[[extensions]]
name = "OMS Label"
handle = "order-label"
type = "ui_extension"

  [[extensions.targeting]]
  module = "./src/OrderLabelExtension.tsx"
  target = "admin.order-details.block.render"
